services:
  ws_postgresql:
    image: postgres:14
    container_name: ws_postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ws_user -d ws_db"]
      interval: 3s
      timeout: 3s
      retries: 5
    # env_file:
    #   - ../ws_api/.env
    volumes:
      - ws_postgres_data:/var/lib/postgresql/data
    networks:
      - ws-network
    

volumes:
  ws_postgres_data:

networks:
  ws-network:
